export const RIDE_STATUS = {
    REQUESTED: 'REQUESTED',
    ACCEPTED: 'ACCEPTED',
    ARRIVED: 'ARRIVED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
};

export const PAYMENT_STATUS = {
    PENDING: 'PENDING',
    PAID: 'PAID',
    FAILED: 'FAILED'
};

export const VEHICLE_TYPE = {
    MOTO: 'MOTO',
    AUTO: 'AUTO',
    UBER_GO: 'UBER_GO',
    PREMIER: 'PREMIER',
    UBER_XL: 'UBER_XL'
};

export const DRIVER_STATUS = {
    PENDING_VERIFICATION: 'PENDING',
    AVAILABLE: 'AVAILABLE',
    ON_RIDE: 'ON_RIDE',
    OFFLINE: 'OFFLINE',
    SUSPENDED: 'SUSPENDED'
};
