# Generated by Django 5.0.6 on 2026-08-04 19:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('MINI', 'Mini'), ('SEDAN', 'Sedan'), ('SUV', 'SUV')], max_length=20)),
                ('plate_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dl_image', models.ImageField(blank=True, null=True, upload_to='dl_uploads/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AVAILABLE', 'Available'), ('OFFLINE', 'Offline'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('current_city', models.CharField(blank=True, db_index=True, max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('verification_note', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.vehicle')),
            ],
        ),
    ]
