# Generated by Django 5.0.6 on 2026-08-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('MOTO', 'Moto'), ('AUTO', 'Auto'), ('UBER_GO', 'Uber Go'), ('PREMIER', 'Premier'), ('UBER_XL', 'Uber XL')], max_length=20),
        ),
    ]
