# Generated by Django 5.0.6 on 2026-08-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AVAILABLE', 'Available'), ('ON_RIDE', 'On Ride'), ('OFFLINE', 'Offline'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
    ]
