# Generated by Django 5.0.6 on 2026-08-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driverprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
