# Generated by Django 5.0.6 on 2026-08-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_route_distance_km_ride_route_duration_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='drop_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
