# Generated by Django 5.0.6 on 2026-08-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_drop_address_ride_pickup_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('MINI', 'Mini'), ('SEDAN', 'Sedan'), ('SUV', 'SUV')], default='MINI', max_length=10),
        ),
    ]
