# Generated by Django 5.0.6 on 2026-08-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ride_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='vehicle_type',
        ),
    ]
