# Generated by Django 5.0.6 on 2026-08-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_remove_ride_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('MINI', 'Mini'), ('SEDAN', 'Sedan'), ('SUV', 'SUV')], default='MINI', max_length=20, null=True),
        ),
    ]
