# Generated by Django 5.0.6 on 2026-08-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_ride_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='drop_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('MOTO', 'Moto'), ('AUTO', 'Auto'), ('UBER_GO', 'Uber Go'), ('PREMIER', 'Premier'), ('UBER_XL', 'Uber XL')], default='MOTO', max_length=20, null=True),
        ),
    ]
