# Generated by Django 5.0.6 on 2026-08-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_alter_ride_drop_address_alter_ride_pickup_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
