# Generated by Django 5.0.6 on 2026-08-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_ride_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='drop_lat',
            field=models.DecimalField(decimal_places=9, max_digits=11),
        ),
        migrations.AlterField(
            model_name='ride',
            name='drop_lng',
            field=models.DecimalField(decimal_places=9, max_digits=11),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_lat',
            field=models.DecimalField(decimal_places=9, max_digits=11),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_lng',
            field=models.DecimalField(decimal_places=9, max_digits=11),
        ),
    ]
