# Generated by Django 6.1 on 2026-08-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_alter_ride_drop_lat_alter_ride_drop_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
